### ISSUE TITLE
Shopping List

### ISSUE THREAD

**Issue by ibraamar** [Integrated-Project-2-UVic-UCC/power-glove#1]
Here you have to define the components required for your projects, where to buy, quantity and price. Of course it can be used components already existing at UVic-UCC, the cost of them will be also accounted in the budget. You have an example of components. In the last sheet, you have a list of recommended suppliers. If you request the material from these providers, the higher probability that your materials arrive on time.

**Comment by omartinezc** [comment]
Hello Ibra, here's what you asked for, I proceed to close this isue due it's completed. Thanks

Description of the material | Quantity | Price [€] | Cost [€] | Provider | Link / website
-- | -- | -- | -- | -- | --
PLA Basic 1kg, 1,75mm diameter, Colour: black | 0.2 | 17.35 | 3.47 | Filament2print | https://filament2print.com/es/pla-basic/693-pla-basic-negro-bobina-1kg.html
Arduino Nano, 5V, Analog Input Pins: 8 | 1 | 19.34 | 19.34 | RS-Online | https://store.arduino.cc/arduino-nano-every
Sensor MPU-9250, 9 DOF, Accel + Gyrosc + Compass | 1 | 8.99 | 8.99 | Amazon | https://www.amazon.es/s?k=mpu9250&__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&ref=nb_sb_noss_2
Flex Sensor 4.5'' SEN-08606 Sparkfun | 5 | 15.42 | 77.1 | Mouser | https://www.mouser.es/ProductDetail/SparkFun/SEN-08606/?qs=%2Fha2pyFaduh7GxZGjJjPHgayB8E9yVsDnBtdchicROnE0aIxtgLlfw==
Flex Sensor 2.2'' SEN-10264 Sparkfun | 5 | 8.95 | 44.75 | Mouser | https://www.mouser.es/ProductDetail/SparkFun/SEN-10264/?qs=%2Fha2pyFadujn%252BXyGtLS0Gd%252B11V7wszMUpEXwoveXI9JPH0dhKp7WTw%3D%3D
