### ISSUE TITLE
Mechanic development 1

### ISSUE THREAD

**Issue by omartinezc** [Integrated-Project-2-UVic-UCC/power-glove#11]
We have developed some very primitive drafts that, later we will pass to 3d design with PTC Creo Parametric
[V2_Blueprints.pdf](https://github.com/Integrated-Project-2-UVic-UCC/power-glove/files/6271962/V2_Blueprints.pdf)

**Comment by josepmaria-carbonell** [comment]
Can you attach the documents or add a link?
