### ISSUE TITLE
PTC-CREO 3D wrist electronics design

### ISSUE THREAD

**Issue by omartinezc** [Integrated-Project-2-UVic-UCC/power-glove#16]
With the first design, we could see that this was still far from a good product in terms of ergonomics, aesthetic design, and optimization of materials (every field it’s important when developing an engineering project). So, as we intended with this first design, we went to a second model improving everything that occurred to us:

- Efficiency of the material (do not use more than necessary)
- Esthetic
- Ergonomics
- Layout of the electronics
- Holes for electronics inputs / outputs

Giving as a resoult the Wrist_V2 design (not final design):

![creo](https://user-images.githubusercontent.com/16194305/112126862-2590d900-8bc5-11eb-9790-d6f9021791e2.jpg)

Blueprints:

[V2_Blueprints.pdf](https://github.com/Integrated-Project-2-UVic-UCC/power-glove/files/6188377/V2_Blueprints.pdf)

**Comment by josepmaria-carbonell** [comment]
Can you attach the documents / pictures of the design / or add a link?

**Comment by omartinezc** [comment]
> Can you attach the documents / pictures of the design / or add a link?

Of course, we'll add the resources on the main (First) comment
