### ISSUE TITLE
Final shopping list

### ISSUE THREAD

**Issue by omartinezc** [Integrated-Project-2-UVic-UCC/power-glove#23]
Hello team, here we will post all the material recived and the remaining to obtain. Also to add new materials if needed.

**Comment by gervidtab** [comment]
![arduino nano](https://user-images.githubusercontent.com/79143352/114424368-55297480-9bb8-11eb-8ce8-0288fe482226.jpeg)
ARDUINO NANO.

**Comment by gervidtab** [comment]
![PCB](https://user-images.githubusercontent.com/79143352/114424697-a9ccef80-9bb8-11eb-9306-d4d36ff7e8ca.jpeg)

ARDUINO NANO with an implanted PCB below it and five resistances of 10kΩ

**Comment by gervidtab** [comment]
![mpu](https://user-images.githubusercontent.com/79143352/114428360-62e0f900-9bbc-11eb-9669-2cee59dc00c5.jpeg)
MPU9250 provided by the University.

**Comment by gervidtab** [comment]
![resistances](https://user-images.githubusercontent.com/79143352/114428446-7ee49a80-9bbc-11eb-99a8-785a44804736.jpeg)
Resistances of 10kΩ.

**Comment by gervidtab** [comment]
![glove](https://user-images.githubusercontent.com/79143352/114428505-958af180-9bbc-11eb-8125-0b3292e6843d.jpeg)
GLOVE

**Comment by gervidtab** [comment]
![flexsensors](https://user-images.githubusercontent.com/79143352/114428602-ae93a280-9bbc-11eb-8a36-4f9f9dc6e99d.jpeg)
FLEXSENSORS.

**Comment by gervidtab** [comment]
![flexsensors](https://user-images.githubusercontent.com/79143352/114429649-e4855680-9bbd-11eb-89ea-3d01c0a29fb1.jpeg)
three flexsensors of 2.18 inches (5.53cm) and two of 3.75 inches (9.52cm). Provider: Spectra Symbol.

**Comment by gervidtab** [comment]
![pla](https://user-images.githubusercontent.com/79143352/114431032-57db9800-9bbf-11eb-8541-2be88358a0df.jpg)
PLA 3D filament. Provider: Smart Materials 3D.

**Comment by gervidtab** [comment]
- Arduino NANO with an implanted PCB below it and five resistances of 10kΩ
- MPU9250 provided by the University.
- Resistances of 10kΩ.
- one glove
- three flexsensors of 2.18 inches (5.53cm) and two of 3.75 inches (9.52cm). Provider: Spectra Symbol.
- PLA 3D filament. Provider: Smart Materials 3D
- fourscrews metric 2
- two pairs of power strips with pins male-male
- twopairs of power strips with pins male-female
