### ISSUE TITLE
Messages for serial comunication. 

### ISSUE THREAD

**Issue by moises-garin** [Integrated-Project-2-UVic-UCC/power-glove#25]
@ibraamar, here you have a real example of how to design the messages in ascii mode for serial comunication.

[http://www.ozeki.hu/p_5855-ozeki-modbus-ascii.html](http://www.ozeki.hu/p_5855-ozeki-modbus-ascii.html)

In you case the bare minimum would be start character, data and CR.

**Comment by ibraamar** [comment]
Thanks Moises.

**Comment by ibraamar** [comment]
Solved
